sudo: required
dist: trusty

language: cpp

script:
  - pushd third_party
  - git clone https://github.com/approvals/ApprovalTests.cpp.git
  - popd
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_CXX_COMPILER=g++-6 ..
  - cmake --build .
  - ctest --verbose

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-6
