sudo: required
dist: trusty

language: cpp

# See https://docs.travis-ci.com/user/languages/cpp/
# Based on https://github.com/catchorg/Catch2/blob/master/.travis.yml

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-3.9
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0
  - llvm-toolchain-trusty-6.0

matrix:
  include:

    # 1/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages: ['clang-5.0', 'libstdc++-8-dev']
      env: CC='clang-5.0' CXX='clang++-5.0'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages: ['clang-6.0', 'libstdc++-8-dev']
      env: CC='clang-6.0' CXX='clang++-6.0'

    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: ['g++-7']
      env: CC='gcc-7' CXX='g++-7'

    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages: ['g++-8']
      env: CC='gcc-8' CXX='g++-8'

# See https://github.com/zie87/sdl2_cxx/blob/fa03e4fdff828284af6f0fa08f7761103ef38ab8/.travis.yml
script:
  - pushd third_party
  - git clone https://github.com/approvals/ApprovalTests.cpp.git
  - cd ApprovalTests.cpp
  - git show --oneline -s
  - popd
  - mkdir .build
  - cd .build
  - cmake ..
  - cmake --build .
  - ctest --verbose
  - cmake --version
