sudo: required
dist: trusty

language: cpp

# See https://docs.travis-ci.com/user/languages/cpp/

#compiler:
#  - clang
#  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

# See https://github.com/zie87/sdl2_cxx/blob/fa03e4fdff828284af6f0fa08f7761103ef38ab8/.travis.yml
script:
  - pushd third_party
  - git clone https://github.com/approvals/ApprovalTests.cpp.git
  - git show --oneline -s
  - popd
  - mkdir .build
  - cd .build
  - cmake ..
  - cmake --build .
  - ctest --verbose
  - env
  - cmake --version

