image: Visual Studio 2017

before_build:
- cmd: >-
    cd third_party
    git clone https://github.com/approvals/ApprovalTests.cpp.git
    cd ..
    cmake .

build:
  project: ApprovalTests.cpp.Nursery.sln

test_script:
- cmd: ctest --verbose --parallel 4 -C Debug
