#!/usr/bin/env bash

dotnet tool update  -g MarkdownSnippets.Tool
mdsnippets \
    --exclude cmake-build:third_party \
    --toc-level 5 --readonly true \
    --header "GENERATED FILE - DO NOT EDIT\nThis file was generated by [MarkdownSnippets](https://github.com/SimonCropp/MarkdownSnippets).\nSource File: {relativePath}\nTo change this file edit the source file and then execute ./run_markdown_templates.sh."
